//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderAutomation.Fanuc.Sample.WindowsDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnderAutomation.Fanuc.Sample.WindowsDesktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right_line {
            get {
                object obj = ResourceManager.GetObject("arrow-right-line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_up_line {
            get {
                object obj = ResourceManager.GetObject("arrow-up-line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add an external item to the view. Use AddNew() or add to source list instead..
        /// </summary>
        internal static string CannotAddItem {
            get {
                return ResourceManager.GetString("CannotAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a new item due to no object being provided in the AddingNew event and a lack of default public constructor..
        /// </summary>
        internal static string CannotAddNewItem {
            get {
                return ResourceManager.GetString("CannotAddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a new item when NewItemsList is null..
        /// </summary>
        internal static string CannotAddWhenNewItemsListNull {
            get {
                return ResourceManager.GetString("CannotAddWhenNewItemsListNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot clear this view..
        /// </summary>
        internal static string CannotClearView {
            get {
                return ResourceManager.GetString("CannotClearView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert an external item into this collection..
        /// </summary>
        internal static string CannotInsertItem {
            get {
                return ResourceManager.GetString("CannotInsertItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set an item in the view..
        /// </summary>
        internal static string CannotSetItem {
            get {
                return ResourceManager.GetString("CannotSetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_bin_5_line {
            get {
                object obj = ResourceManager.GetObject("delete-bin-5-line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_2_line {
            get {
                object obj = ResourceManager.GetObject("download-2-line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_edit_line {
            get {
                object obj = ResourceManager.GetObject("file-edit-line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_line {
            get {
                object obj = ResourceManager.GetObject("file-line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_add_line {
            get {
                object obj = ResourceManager.GetObject("folder-add-line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_line {
            get {
                object obj = ResourceManager.GetObject("folder-line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_shared_line {
            get {
                object obj = ResourceManager.GetObject("folder-shared-line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to includeDelegate cannot be null..
        /// </summary>
        internal static string IncludeDelegateCannotBeNull {
            get {
                return ResourceManager.GetString("IncludeDelegateCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item in list is not of type {0}..
        /// </summary>
        internal static string InvalidListItemType {
            get {
                return ResourceManager.GetString("InvalidListItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source list does not implement IList..
        /// </summary>
        internal static string InvalidSourceList {
            get {
                return ResourceManager.GetString("InvalidSourceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item was not of type {0}..
        /// </summary>
        internal static string ItemTypeIncorrect {
            get {
                return ResourceManager.GetString("ItemTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no filter).
        /// </summary>
        internal static string NoFilter {
            get {
                return ResourceManager.GetString("NoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object cannot be null..
        /// </summary>
        internal static string ObjectCannotBeNull {
            get {
                return ResourceManager.GetString("ObjectCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (predicate filter).
        /// </summary>
        internal static string PredicateFilter {
            get {
                return ResourceManager.GetString("PredicateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} does not exist in type {1}..
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_line {
            get {
                object obj = ResourceManager.GetObject("refresh-line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_3_fill {
            get {
                object obj = ResourceManager.GetObject("save-3-fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source list already added to the view..
        /// </summary>
        internal static string SourceListAlreadyAdded {
            get {
                return ResourceManager.GetString("SourceListAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source list is not in the view..
        /// </summary>
        internal static string SourceListNotFound {
            get {
                return ResourceManager.GetString("SourceListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceLists cannot be null..
        /// </summary>
        internal static string SourceListsNull {
            get {
                return ResourceManager.GetString("SourceListsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized access to the view is not supported..
        /// </summary>
        internal static string SyncAccessNotSupported {
            get {
                return ResourceManager.GetString("SyncAccessNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tools_line {
            get {
                object obj = ResourceManager.GetObject("tools-line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ua {
            get {
                object obj = ResourceManager.GetObject("ua", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnderAutomation132 {
            get {
                object obj = ResourceManager.GetObject("UnderAutomation132", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upload_2_line {
            get {
                object obj = ResourceManager.GetObject("upload-2-line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
